description=bad, instanceof FooException
expected_problems=1