description=ok, super.finalize called in try..catch..finally
expected_problems=0