description=throw exception but return from finally
expected_problems=1