description=Ok when throwing another exception
expected_problems=0